# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='mark',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u041e\u0446\u0435\u043d\u043a\u0430'),
        ),
    ]
