# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformators', '0002_auto_20170530_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupil',
            options={'verbose_name': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442', 'verbose_name_plural': '\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b'},
        ),
        migrations.AlterField(
            model_name='pupil',
            name='mark',
            field=models.IntegerField(null=True, verbose_name='\u041e\u0446\u0435\u043d\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='test_number',
            field=models.IntegerField(null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u0441\u0442\u0430'),
        ),
    ]
