# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transformators', '0003_auto_20170530_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
    ]
