# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformators', '0004_remove_answer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='wrong_answers',
            field=models.TextField(default='', verbose_name='\u041d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0435 \u043e\u0442\u0432\u0435\u0442\u044b'),
            preserve_default=False,
        ),
    ]
